-- This script has been moved to ServerScriptService/MatchManager.lua
-- The match management logic is now centralized so all stages use the same code.
-- Delete this file and ensure MatchManager.lua is running in ServerScriptService.
